services:
  postgres:
    image: postgres:16
    container_name: soc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soc_license
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d soc_license"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: soc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 5s
      retries: 10

  management-api-service:
    build:
      context: ./apps/management-api-service
    container_name: management-api-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soc_license
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  frontend:
    build:
      context: ./apps/frontend
      args:
        VITE_MANAGEMENT_API_URL: ""
        VITE_COLLECTOR_API_URL: ""
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - management-api-service


  event-producer-otel:
    build:
      context: ./apps/event-producer-otel
    container_name: event-producer-otel
    environment:
      COLLECTOR_URL: http://otel-custom-collector:4318
      TENANT_IDS: 481a6ae5-8e14-4899-80b3-d95feb5a3395
      EPS: 100
      BATCH_SIZE: 50
    depends_on:
      - otel-custom-collector

  otel-custom-collector:
    build:
      context: ./apps/otel-custom-collector
    container_name: otel-custom-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: