receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  soc_license_processor:
    redis_url: "soc-redis:6379"
  batch:
    send_batch_size: 100
    timeout: 1s

exporters:
  logging:
    verbosity: detailed
  kafka:
    protocol_version: 2.0.0
    brokers:
      - soc-kafka:9092
    topic: soc-logs
    encoding: otlp_json

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [soc_license_processor, batch]
      exporters: [logging, kafka]
