server.port=${SERVER_PORT:8080}
spring.application.name=management-api-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:soc_license}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=health,info

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=d6fa650046aaef
spring.mail.password=d3201f61529a28
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Security (OAuth2 / Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/soc-platform
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8180/realms/soc-platform/protocol/openid-connect/certs

# Keycloak Admin Client
keycloak.admin.server-url=http://keycloak:8180
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}